export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIG_IN_START: "GOOGLE_SIG_IN_START",
  EMAIL_SIG_IN_START: "EMAIL_SIG_IN_START",
  SIG_IN_SUCCESS: "SIG_IN_SUCCESS",
  SIG_IN_FAILURE: "SIG_IN_FAILURE",
};
