export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  GOOGLE_SIG_IN_START: "GOOGLE_SIG_IN_START",
  GOOGLE_SIG_IN_SUCCESS: "GOOGLE_SIG_IN_SUCCESS",
  GOOGLE_SIG_IN_FAILURE: "GOOGLE_SIG_IN_FAILURE",
  EMAIL_SIG_IN_START: "EMAIL_SIG_IN_START",
  EMAIL_SIG_IN_SUCCESS: "EMAIL_SIG_IN_SUCCESS",
  EMAIL_SIG_IN_FAILURE: "EMAIL_SIG_IN_FAILURE",

}